### ISSUE TITLE
Convert switch functions to dictionaries

### ISSUE THREAD

**Issue by maxpinheiro** [sandboxnu/a-eye#111]
There are several gross functions throughout the modules that use switch statements to map from strings to objects (components, images, etc). I noticed Jake achieved the same functionality with a dictionary, so we should get rid of all of those switches.
- **switch functions to change**:  GetImage and getDemo in ModuleSection.tsx, getCoverImage in ModuleIntro.tsx
- example of converting from switch to dictionary: [link](https://coderwall.com/p/s7592q/use-dictionary-lookups-instead-of-switch-statements)

**Comment by jakeisnt** [comment]
:+1: dictionaries are just better. even for the complicated expressions, you can just stash lambdas in the dictionary - unlike using a `switch` this either lets you give each expression a name or allows you to more easily move more logic out of the component which makes things easier to read
